apiVersion: v1
kind: Pod
metadata:
  name: queue-initializer
spec:
  containers:
    - name: swat-container
      image: swat:1.0
      command: ["/bin/bash", "/workspace/declare_queue.sh"]
      env:
        - name: BROKER_URL
        value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
        value: taskqueque
        - name: RNO
        value: 2
        - name: VNO
        value: 7
      volumeMounts:
        - mountPath: /var/local/input/
        name: input
        - mountPath: /var/local/output/
        name: output
  volumes:
      - name: input
      hostPath:
        path: /run/desktop/mnt/host/d/docker/input/
        type: Directory
      - name: output
        hostPath:
          path: /run/desktop/mnt/host/d/docker/output/
          type: Directory
  restartPolicy: OnFailure
