apiVersion: v1
kind: Pod
metadata:
  name: queue-initializer
spec:
  containers:
    - name: swat-container
      image: jannyarj/swat:1.1
      #image: jannyarj/swat:1.0
      command: ["/bin/bash", "/model/declare_queue.sh"]
      #keep containner alive
      #command: ["tail"]
      #args: ["-f", "/dev/null"]
      volumeMounts:
        - name: model
          mountPath: /model/
  volumes:
      - name: model
        hostPath:
          path: /run/desktop/mnt/host/d/docker/version2/project
          type: Directory
  restartPolicy: OnFailure
