apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq_pod
  labels:
    app: taskQueue
    component: rabbitmq
spec:
  containers:
    - image: rabbitmq
      name: rabbitmq
      ports:
        - containerPort: 5672
